CREATE TABLE IF NOT EXISTS `user_settings` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  `chat_id` INT(12) NOT NULL,
  `language` VARCHAR(3) NOT NULL DEFAULT 'ru',
  `timezone` VARCHAR(32) NOT NULL DEFAULT 'Europe/Moscow',
  `interval_alert` INT(4) NOT NULL DEFAULT 20,
  `take_photo` BOOLEAN NOT NULL DEFAULT FALSE,
  `urgency_enabled` BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE UNIQUE INDEX IF NOT EXISTS us_chat_id_idx ON `user_settings` (`chat_id`);

CREATE TABLE IF NOT EXISTS `notifications` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  `chat_id` INT(12) NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  `time` CHAR(5) NOT NULL,
  `dosage` VARCHAR(32) NOT NULL,

  `enabled` BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE INDEX IF NOT EXISTS nfs_chat_id_idx ON `notifications` (`chat_id`);

CREATE TABLE IF NOT EXISTS `history` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

  `chat_id` INT(12) NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  `dosage` VARCHAR(32) NOT NULL
);
CREATE INDEX IF NOT EXISTS hst_chat_id_idx ON `history` (`chat_id`);
